sudo: false

dist: trusty

language: python

python:
  - "2.7"
  
# command to install dependencies
install:
  - pip install -r requirements.txt

notifications:
  email:
    recipients:
    - martinjrobins@gmail.com
    - michael.clerx@cs.ox.ac.uk 
