name: Notebooks

on:
  schedule:
    # 4am daily
    - cron:  '0 4 * * *'

jobs:

  build-and-test:
    name: Notebooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: install pints
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
          python -m pip install .[dev]

      - name: run jupyter notebooks
        run: |
          python run-tests.py --books
