name: Unit tests (OS versions)

on:
  push:
    branches:
      - master
  pull_request:
    # Run workflow when PR is changed, or when changed from draft to ready
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    if: github.event.pull_request.draft == false
    name: OS unit tests
    runs-on: ${{ matrix.os }}

    # Skip job if it's a draft PR
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: install pints
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .

      - name: run unit tests
        run: |
          python run-tests.py --unit
